import {
  SiReact,
  SiNextdotjs,
  SiPrisma,
  SiDocker,
  SiAmazonwebservices,
  SiCloudflare,
  SiServerless,
  SiVim,
  SiVisualstudiocode,
  SiExpress,
  SiPython,
  SiFastapi,
  SiMysql,
  SiPostgresql,
  SiOpenai,
  SiFigma,
  SiLinux,
  SiTypescript,
  SiJavascript,
  SiGit,
  SiTailwindcss,
  SiC,
  SiCplusplus,
  SiNeovim,
  SiHtml5,
  SiCss3,
  SiJquery,
  SiRedux,
  SiGraphql,
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiAnsible,
  SiArduino,
  SiBabel,
  SiBootstrap,
  SiChakraui,
  SiCircleci,
  SiCloudera,
  SiDigitalocean,
  SiDjango,
  SiDotnet,
  SiElastic,
  SiElectron,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGimp,
  SiGitlab,
  SiGo,
  SiHaskell,
  SiHeroku,
  SiHomeassistant,
  SiInkscape,
  SiJenkins,
  SiJetbrains,
  SiJoomla,
  SiJulia,
  SiKibana,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLatex,
  SiMagento,
  SiMicrosoftazure,
  SiMongodb,
  SiNginx,
  SiNpm,
  SiNumpy,
  SiOpencv,
  SiOracle,
  SiPandas,
  SiPhp,
  SiPowerbi,
  SiPytorch,
  SiR,
  SiRaspberrypi,
  SiRedis,
  SiReduxsaga,
  SiRust,
  SiSass,
  SiScala,
  SiSnowflake,
  SiSpring,
  SiStyledcomponents,
  SiSwift,
  SiTableau,
  SiTensorflow,
  SiTerraform,
  SiUnity,
  SiUnrealengine,
  SiWebpack,
  SiWordpress,
  SiXamarin,
  SiYarn,
} from "react-icons/si";
const icons = [
  { id: 1, component: SiReact, color: "#61DAFB" },
  { id: 2, component: SiNextdotjs, color: "black" },
  // { id: 3, component: SiPrisma, color: "#2D3748" },
  // { id: 4, component: SiDocker, color: "#2496ED" },
  // { id: 5, component: SiAmazonwebservices, color: "#FF9900" },
  // { id: 6, component: SiCloudflare, color: "#F38020" },
  // { id: 7, component: SiServerless, color: "#FD5750" },
  // { id: 8, component: SiVim, color: "#019733" },
  // { id: 9, component: SiVisualstudiocode, color: "#007ACC" },
  // { id: 10, component: SiExpress, color: "black" },
  // { id: 11, component: SiPython, color: "#3776AB" },
  // { id: 12, component: SiFastapi, color: "#05998B" },
  // { id: 13, component: SiMysql, color: "#4479A1" },
  // { id: 14, component: SiPostgresql, color: "#336791" },
  // { id: 15, component: SiOpenai, color: "#412991" },
  // { id: 16, component: SiFigma, color: "#F24E1E" },
  // { id: 17, component: SiLinux, color: "yellow" },
  // { id: 18, component: SiTypescript, color: "#2496ED" },
  // { id: 19, component: SiJavascript, color: "yellow" },
  // { id: 20, component: SiGit, color: "maroon" },
  // { id: 21, component: SiTailwindcss, color: "skyblue" },
  // { id: 22, component: SiC, color: "gray" },
  // { id: 23, component: SiCplusplus, color: "lightblue" },
  // { id: 24, component: SiNeovim, color: "#57A143" },
  // { id: 25, component: SiHtml5, color: "#E34F26" },
  // { id: 26, component: SiCss3, color: "#1572B6" },
  // { id: 27, component: SiJquery, color: "#0769AD" },
  // { id: 28, component: SiRedux, color: "#764ABC" },
  // { id: 29, component: SiGraphql, color: "#E10098" },
  // { id: 30, component: SiSass, color: "#CC6699" },
  // { id: 31, component: SiDjango, color: "#092E20" },
  // { id: 32, component: SiFlask, color: "black" },
  // { id: 33, component: SiGo, color: "#00ADD8" },
  // { id: 34, component: SiRust, color: "#DEA584" },
  // { id: 35, component: SiKubernetes, color: "#326CE5" },
  // { id: 36, component: SiTerraform, color: "#623CE4" },
  // { id: 37, component: SiAnsible, color: "#EE0000" },
  // { id: 38, component: SiJenkins, color: "#D24939" },
  // { id: 39, component: SiMongodb, color: "#47A248" },
  // { id: 40, component: SiFirebase, color: "#FFCA28" },
  // { id: 41, component: SiRedis, color: "#DC382D" },
  // { id: 42, component: SiNginx, color: "#009639" },
  // { id: 43, component: SiWebpack, color: "#8DD6F9" },
  // { id: 44, component: SiBabel, color: "#F9DC3E" },
  // { id: 45, component: SiKibana, color: "#005571" },
  // { id: 46, component: SiElastic, color: "#005571" },
  // { id: 47, component: SiCircleci, color: "#343434" },
  // { id: 48, component: SiDigitalocean, color: "#0080FF" },
  // { id: 49, component: SiHeroku, color: "#430098" },
  // { id: 50, component: SiMicrosoftazure, color: "#0078D4" },
  // { id: 51, component: SiGitlab, color: "#FCA121" },
  // { id: 52, component: SiNpm, color: "#CB3837" },
  // { id: 53, component: SiYarn, color: "#2C8EBB" },
  // { id: 54, component: SiBootstrap, color: "#7952B3" },
  // { id: 55, component: SiStyledcomponents, color: "#DB7093" },
  // { id: 56, component: SiChakraui, color: "#319795" },
  // { id: 57, component: SiFlutter, color: "#02569B" },
  // { id: 58, component: SiElectron, color: "#47848F" },
  // { id: 59, component: SiReduxsaga, color: "#999999" },
  // { id: 60, component: SiNumpy, color: "#013243" },
  // { id: 61, component: SiPandas, color: "#150458" },
  // { id: 62, component: SiOpencv, color: "#5C3EE8" },
  // { id: 63, component: SiTensorflow, color: "#FF6F00" },
  // { id: 64, component: SiPytorch, color: "#EE4C2C" },
  // { id: 65, component: SiTableau, color: "#E97627" },
  // { id: 66, component: SiOracle, color: "#F80000" },
  // { id: 67, component: SiSnowflake, color: "#56B9EB" },
  // { id: 68, component: SiWordpress, color: "#21759B" },
  // { id: 69, component: SiMagento, color: "#EE672F" },
  { id: 70, component: SiJoomla, color: "#F44321" },
  { id: 71, component: SiLaravel, color: "#FF2D20" },
  { id: 72, component: SiSpring, color: "#6DB33F" },
  { id: 73, component: SiDotnet, color: "#5C2D91" },
  { id: 74, component: SiXamarin, color: "#3498DB" },
  { id: 75, component: SiUnity, color: "#222C37" },
  { id: 76, component: SiUnrealengine, color: "#0E1128" },
  { id: 77, component: SiRaspberrypi, color: "#C51A4A" },
  { id: 78, component: SiArduino, color: "#00979D" },
  { id: 79, component: SiHomeassistant, color: "#41BDF5" },
  { id: 80, component: SiJetbrains, color: "#000000" },
  { id: 81, component: SiPhp, color: "#777BB4" },
  { id: 82, component: SiScala, color: "#DC322F" },
  { id: 83, component: SiHaskell, color: "#5D4F85" },
  { id: 84, component: SiLatex, color: "#008080" },
  // { id: 85, component: SiInkscape, color: "#000000" },
  // { id: 86, component: SiGimp, color: "#5C5543" },
  // { id: 87, component: SiAdobephotoshop, color: "#31A8FF" },
  // { id: 88, component: SiAdobeillustrator, color: "#FF9A00" },
  // { id: 89, component: SiKotlin, color: "#0095D5" },
  // { id: 90, component: SiSwift, color: "#FA7343" },
  // { id: 91, component: SiR, color: "#276DC3" },
  // { id: 92, component: SiJulia, color: "#9558B2" },
  // { id: 93, component: SiCloudera, color: "#F88900" },
  // { id: 94, component: SiPowerbi, color: "#F2C811" },
];

export default icons;
